# Generated by Django 4.1 on 2022-08-07 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=uuid.UUID('56cdaa6c-91d0-4f33-b0ed-42c37474cf4a'), max_length=256),
        ),
    ]
